### ISSUE TITLE
Issues with recurring when connecting with Strava

### ISSUE THREAD

**Issue by OleksiyRudenko** [Gerben321/bike-care-tracker#6] opened 2024-01-17 16:56 UTC
**Describe the bug**
Context: I was connected with Strava before, so having an account with the BikeCare already setup.
Today's experience ends in inability to login to BikeCare using Connect with Strava feature, resulting in error.

**To Reproduce**
1. Go to https://bikecare.gerbenbol.com/
3. Click on `Connect with Strava` and get redirected to Strava
4. Click `Authorize` at Strava (all permissions are checked) and get redirected back to BikeCare, page https://bikecare.gerbenbol.com/dashboard/login
5. See error `Something went wrong...` on the page (see screenshot below)

On Android v13 Chrome browser same STR results in:
4. Click `Authorize` at Strava (all permissions are checked) and get redirected back to BikeCare, page https://bikecare.gerbenbol.com/strava-login?state=e27d07967e0992625231d5ea25e3d736&code=a46692a0848dcc80e4d37acfe75d9c978f6db4bb&scope=read,activity:read_all,profile:read_all,read_all
5. See error `Invalid state` on an empty page (see screenshot below)

**Expected behavior**
BikeCare dashboard

**Screenshots**
Desktop
<img width="750" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/dfe8ae27-1152-4690-9723-cf8dad48acd4" />

Mobile
<img width="350" src="https://github.com/Gerben321/bike-care-tracker/assets/8686631/0a2ee56c-ff2c-4044-b6f8-2671ab52a3a4" />

**Desktop (please complete the following information):**
 - OS: MacOS v13
 - Browser: Chrome
 - Version: 120.0.6099.216 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 13
 - Browser Chrome
 - Version 120.0.6099.210

**Additional context**

**Comment by OleksiyRudenko** [comment] 2024-01-17 18:51
@Gerben321 thank you for looking into this.
It works for me now on desktop. Weirdly, on Android Chrome the issue persists.

**Comment by Gerben321** [comment] 2024-01-17 18:53
Seems like this was introduced after some changes earlier today. I fixed one error, but indeed the 'invalid state' is still present. Now looking what's wrong with that. I'll let you know when there's news.

**Comment by Gerben321** [comment] 2024-01-17 19:05
@OleksiyRudenko Should be fixed now. Maybe the Strava screen pops up twice, will try to fix that as well. But you should get in again on all devices. You should also be logged in for longer now.

**Comment by Gerben321** [comment] 2024-01-17 19:28
Seems like the issue is that the browser is somehow caching a URL. So that explains the different behaviour in different browsers. It's working fine for me in private mode, while I get the cached Strava login URL on my normal browser mode. Gonna have to look if that's something I can disable.

**Comment by Gerben321** [comment] 2024-01-17 19:43
Should be fixed now if you try again. I've added a random hash to the big orange Strava button to make sure it's not cached. Let me know if it fixes it for you on all your devices.

**Comment by OleksiyRudenko** [comment] 2024-01-17 20:39
@Gerben321 tested. Was stuck on Strava authorization page, i.e. clicking on Authorize didn't actually redirect back to BikeCare. After several attempts it let me through.
As a result, I am successfully logged in on BikeCare and logged-in state persists/survives page reload.
I'd consider it resolved until the issue reoccurs.
Thank you

**Closed** 2024-01-17 20:41 UTC
Labels: bug

**Comment by Gerben321** [comment] 2024-01-18 08:25
Little false alarm about remaining logged in, wasn't fully working. If you log out and login again now, you will stay logged in for a month.
